### PR TITLE
feat(firestore): add samples for sum and average

### PR DESCRIPTION
**Pull request by Lyokone**
_Description of what this PR is changing or adding:_

_Issues fixed by this PR (if any): https://github.com/firebase/flutterfire/issues/13062

## Risk Level
- [x] No risk
- [ ] Somewhat Risky
- [ ] High risk

## Pre-submit checklist
- [ ] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style)
- [ ] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks)

### CODE REVIEW

**Review by thatfiredev — COMMENTED** [review]
Thanks @Lyokone ! Two comments:

1. The [current examples](https://firebase.google.com/docs/firestore/query-data/aggregation-queries#use_the_sum_aggregation) in the docs use the `cities` example, can we use that same collection for consistency? (I have added suggested edits below)
2. Can you please also add a snippet for [multiple aggregations in a query](https://firebase.google.com/docs/firestore/query-data/aggregation-queries#calculate_multiple_aggregations_in_a_query)?

**Comment by cynthiajoan** [comment]
> Thanks @Lyokone ! Two comments:
> 
> 1. The [current examples](https://firebase.google.com/docs/firestore/query-data/aggregation-queries#use_the_sum_aggregation) in the docs use the `cities` example, can we use that same collection for consistency? (I have added suggested edits below)
> 2. Can you please also add a snippet for [multiple aggregations in a query](https://firebase.google.com/docs/firestore/query-data/aggregation-queries#calculate_multiple_aggregations_in_a_query)?

Thanks @thatfiredev for the review. In this case, should we also update the count snippets to use cities example?

**Comment by thatfiredev** [comment]
@cynthiajoan Oh, I hadn't noticed that one was using a different example. Yes, let's use cities there too please. :)

**Comment by cynthiajoan** [comment]
> Hmmm, not sure why CI is failing (both here and in #36), but some [posts](https://github.com/jonataslaw/get_cli/issues/263) suggest upgrading packages. Can we try that @Lyokone ?
> 
> Error log for reference:
> 
> ```
> ../../../../../.pub-cache/hosted/pub.dev/win32-5.0.6/lib/src/guid.dart:32:9: Error: Type 'UnmodifiableUint8ListView' not found.
>   final UnmodifiableUint8ListView bytes;
>         ^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../../../../.pub-cache/hosted/pub.dev/win32-5.0.6/lib/src/guid.dart:32:9: Error: 'UnmodifiableUint8ListView' isn't a type.
>   final UnmodifiableUint8ListView bytes;
>         ^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../../../../.pub-cache/hosted/pub.dev/win32-5.0.6/lib/src/guid.dart:52:17: Error: Method not found: 'UnmodifiableUint8ListView'.
>     return Guid(UnmodifiableUint8ListView(guid));
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../../../../.pub-cache/hosted/pub.dev/win32-5.0.6/lib/src/guid.dart:56:31: Error: Method not found: 'UnmodifiableUint8ListView'.
>   factory Guid.zero() => Guid(UnmodifiableUint8ListView(Uint8List(16)));
>                               ^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../../../../.pub-cache/hosted/pub.dev/win32-5.0.6/lib/src/guid.dart:100:17: Error: Method not found: 'UnmodifiableUint8ListView'.
>     return Guid(UnmodifiableUint8ListView(Uint8List.fromList(guidAsBytes)));
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^
> Target kernel_snapshot_program failed: Exception
> 
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script '/home/runner/work/snippets-flutter/snippets-flutter/_flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1687
> 
> * What went wrong:
> Execution failed for task ':app:compileFlutterBuildDebug'.
> > Process 'command '/home/runner/work/snippets-flutter/snippets-flutter/_flutter/bin/flutter'' finished with non-zero exit value 1
> ```

https://github.com/firebase/snippets-flutter/pull/38 to try fixing the CI

**Review by thatfiredev — APPROVED** [review]
Thanks for fixing CI @cynthiajoan !

I'll update https://firebase.google.com/docs/firestore/query-data/aggregation-queries accordingly.

**Pull request merged**
