### PR TITLE
docs:  add snippet for a subcollection query

### PR DESCRIPTION
**Pull request by jlara310**
Add a beginner-level snippet that shows how to query a subcollection.
Similar PR for Android: https://github.com/firebase/snippets-android/pull/447 
Note that I added two snippet tags: one for the convention used by the file and one for
the convention used on cloud.google.com

## Risk Level
- [ x ] No risk
- [ ] Somewhat Risky
- [ ] High risk

## Pre-submit checklist
- [ x] This PR follows the [Google Developer Documentation Style Guidelines](https://developers.google.com/style)
- [ x] This PR uses [semantic line breaks](https://github.com/dart-lang/site-shared/blob/main/doc/writing-for-dart-and-flutter-websites.md#semantic-line-breaks)

### CODE REVIEW

**Review by nohe427 — APPROVED** [review]
LGTM 👍

**Comment by nohe427** [comment]
@thatfiredev -> Do you know why CI/CD might be breaking?

**Comment by thatfiredev** [comment]
@nohe427 It looks like `count()` was introduced in [FlutterFire Firestore v4.0.0](https://github.com/flutter/io_flip/blob/b5b3a23f8aa7731c8e98a98a27aa0cd21c1b8764/README.md?plain=1#L55), but CI is using 3.1.11:

```
lib/snippets/firestore.dart:827:28: Error: The method 'count' isn't defined for the class 'CollectionReference<Map<String, dynamic>>'.
 - 'CollectionReference' is from 'package:cloud_firestore/cloud_firestore.dart' ('../../../../../.pub-cache/hosted/pub.dev/cloud_firestore-3.1.11/lib/cloud_firestore.dart').
 - 'Map' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'count'.
```

**Comment by thatfiredev** [comment]
Oh, looks like 3.1.x is coming from `pubspec.yaml`:

https://github.com/firebase/snippets-flutter/blob/36812ac93095d36ebe10bed2f08793e5f7dfcb06/packages/firebase_snippets_app/pubspec.yaml#L27

**Comment by nohe427** [comment]
@jlara310 - Could you run `flutter pub upgrade --major-versions` to see if that helps get CI to run successfully?

**Comment by jlara310** [comment]
> @jlara310 - Could you run `flutter pub upgrade --major-versions` to see if that helps get CI to run successfully?

Done, but I encountered additional errors when trying to run the app locally. Filed bugs here:

* #24
* #25
* #26

**Comment by thatfiredev** [comment]
@jlara310 Thanks for filing those. Can you commit your current pubspec files after you ran that command so that CI can pick it up?

**Comment by jlara310** [comment]
> @jlara310 Thanks for filing those. Can you commit your current pubspec files after you ran that command so that CI can pick it up in this PR?

Yep. Done.

**Comment by nohe427** [comment]
I am going to merge this since it seems the last few merges were also failing. I will then go through and try and fix the logged bugs. Thanks for making these changes and documenting the new errors. This will give us a great launching off point. @thatfiredev - I will ask you for reviews :)

**Pull request merged**
